### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by tatonki1** [shoreditch-ops/llama-cli#14]
Hi - trying to deploy this to my aws account; have everything setup on the AWS side and I am behind a corporate proxy; but I have set my HTTP-PROXY & HTTPS-PROXY env vars in my shell and can run the aws cli w/ out a problem, yet still receiving this error...any suggestions to get around this?  thanks.

LIBP45P-16600WL:.aws n0224265$ llama deploy -r $LAMBDA_ROLE_ARN

Something went wrong:
{ Error: connect ETIMEDOUT 54.236.138.8:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  message: 'connect ETIMEDOUT 54.236.138.8:443',
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.236.138.8',
  port: 443,
  region: 'us-east-1',
  hostname: 'lambda.us-east-1.amazonaws.com',
  retryable: true,
  time: 2017-03-16T18:55:39.380Z }

**Comment by hassy** [comment]
Looks like it needs to be supported explicitly rather than being configurable through the environment: http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html
